### ISSUE TITLE
Keyboard Input LIMITED to 2 at a time

### ISSUE THREAD

**Issue by Psukeo** [RetroPie/pisnes#3]
Hey.

So, I've been playing Rockman X on PiSNES, and I noticed something: I couldn't do 3 or more key inputs. It really limited me to only moving and shooting, jumping and shooting, or moving and jumping. It really limits your field of activities, because Rockman X, or Mega Man X, as you probably know, have many situations where 3 or more button inputs can really help you in a pinch, like Sigma's first form. Just wondering if you fix it.

-Psukeo

**Comment by rcso2010** [comment]
It's a hardware limitation on the keyboards. You can change the action keys to CTRL, ALT or SHIFT to bypass this behaviour.

**Comment by joolswills** [comment]
Thanks @rcso2010
