### ISSUE TITLE
Logitech Dual Action gamepad issues

### ISSUE THREAD

**Issue by baronvertigovongrahamthesecondofsealand** [RetroPie/pisnes#4]
joytest shows the gamepad working properly. I have buttons 0 through 11, and 5 axes all responding.

snes9x picks up the D-pad buttons, but no other buttons. Ive tried all kinds of mapping combos and cant find anything that works. What gives?

**Comment by joolswills** [comment]
pisnes is not developed here - upstream repo is here - https://sourceforge.net/projects/pisnes/ however it may just be a limitation of the emulator. I recommend using one of the libretro emulators though. Please use the RetroPie forum for more help.
